### ISSUE TITLE
Request - inline options

### ISSUE THREAD

**Issue by opheliadesign** [creativeorange/gravatar#1]
Love this package! It would be really nice to be able to set some options inline, such as the size. Finding that I am duplicating my configuration array several times for different image sizes.

Sorry, not familiar with how to label this as a request.. :)

**Comment by creativeorange** [comment]
Hi @opheliadesign, thanks for loving this package, great to hear!
It is already possible to do this. Instead of passing a configuration key, you could pass an array, which will be merged with the default group. So you could do something like this: 

```php
Gravatar::get('email@example.com', ['size'=>200]); 
```

I know the documentation is not very clear about this, I will update this soon.

**Comment by opheliadesign** [comment]
@creativeorange that's awesome! Glad I asked. Thanks so much! :+1:  :)

**Comment by creativeorange** [comment]
You're welcome. Enjoy!
